### ISSUE TITLE
Amazon Athena support

### ISSUE THREAD

**Issue by sinanerdem** [TileDB-Inc/TileDB-Presto#1]
I wonder if this connector can somehow be used with Amazon Athena to query TileDB data directly from S3? 

https://docs.aws.amazon.com/athena/latest/ug/connect-data-source-federation-sdk.html

**Comment by DimitrisStaratzis** [comment]
Hi @sinanerdem,

Thank you for opening the issue. It seems that to achieve this we would have to add Arrow Buffer support. It is likely several months away on our side due to other development work, but if you are interested in working on this we are very happy to discuss the implementation and review pull-requests in the meantime.

Best,
Dimitris
